package english

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestPostgresQueryQualifiesTablesAndRebindsParameters(t *testing.T) {
	store := &Store{dialect: dialectPostgres}
	got := store.query(`SELECT * FROM lessons l JOIN reading_attempts r ON r.lesson_id=l.id WHERE l.user_id=? AND r.id>?`)
	want := `SELECT * FROM english.lessons l JOIN english.reading_attempts r ON r.lesson_id=l.id WHERE l.user_id=$1 AND r.id>$2`
	if got != want {
		t.Fatalf("query = %q, want %q", got, want)
	}
}

func TestDatabaseDateAndTimeScanBothBackends(t *testing.T) {
	var date databaseDate
	if err := date.Scan(time.Date(2026, 9, 10, 0, 0, 0, 0, time.UTC)); err != nil || date != "2026-09-10" {
		t.Fatalf("PostgreSQL date scan = %q, %v", date, err)
	}
	var timestamp databaseTime
	if err := timestamp.Scan("2026-09-10T08:09:10.123Z"); err != nil || timestamp.UTC().Format(time.RFC3339Nano) != "2026-09-10T08:09:10.123Z" {
		t.Fatalf("SQLite timestamp scan = %v, %v", timestamp.Time, err)
	}
}

func TestEnglishPostgresMigrationCoversUserTables(t *testing.T) {
	raw, err := os.ReadFile("../../migrations/postgres/000004_english_business_data.up.sql")
	if err != nil {
		t.Fatal(err)
	}
	sql := string(raw)
	for _, table := range userScopedTables {
		if !strings.Contains(sql, "CREATE TABLE english."+table) {
			t.Errorf("PostgreSQL migration 缺少 %s", table)
		}
	}
	for _, guard := range []string{
		"FOREIGN KEY (lesson_id, user_id)",
		"FOREIGN KEY (speaking_attempt_id, user_id)",
		"GENERATED BY DEFAULT AS IDENTITY",
		"REFERENCES account.users(id) ON DELETE CASCADE",
	} {
		if !strings.Contains(sql, guard) {
			t.Errorf("PostgreSQL migration 缺少约束 %q", guard)
		}
	}
}

func TestMarshalArrayNormalizesNil(t *testing.T) {
	var values []string
	if got := marshalArray(values); got != "[]" {
		t.Fatalf("marshalArray(nil) = %s", got)
	}
}

func TestPostgresStoreAndSQLiteImportIntegration(t *testing.T) {
	databaseURL := os.Getenv("ENGLISH_TEST_DATABASE_URL")
	if databaseURL == "" {
		t.Skip("ENGLISH_TEST_DATABASE_URL 未配置")
	}
	ctx := context.Background()
	target, err := OpenPostgresStore(ctx, databaseURL)
	if err != nil {
		t.Fatal(err)
	}
	defer target.Close()

	const runtimeUser = "11111111-1111-4111-8111-111111111111"
	const importedUser = "22222222-2222-4222-8222-222222222222"
	for _, userID := range []string{runtimeUser, importedUser} {
		_, _ = target.db.ExecContext(ctx, `DELETE FROM account.users WHERE id::text=$1`, userID)
		if _, err := target.db.ExecContext(ctx, `INSERT INTO account.users(id,status) VALUES($1,'active')`, userID); err != nil {
			t.Fatal(err)
		}
		defer target.db.ExecContext(ctx, `DELETE FROM account.users WHERE id::text=$1`, userID)
	}

	lesson, _, err := target.PutLesson(ctx, Lesson{
		UserID: runtimeUser, Date: "2026-09-10", Title: "Runtime", Passage: "Practice.", Difficulty: 2,
		Questions: []Question{{ID: "q1", Answer: "A"}},
	})
	if err != nil {
		t.Fatal(err)
	}
	reading, err := target.SaveReadingAttempt(ctx, runtimeUser, lesson.ID, []Answer{{QuestionID: "q1", Value: "A"}})
	if err != nil || reading.ID == 0 {
		t.Fatalf("PostgreSQL reading = %+v, %v", reading, err)
	}
	if _, err := target.db.ExecContext(ctx, `DELETE FROM account.users WHERE id::text=$1`, runtimeUser); err != nil {
		t.Fatal(err)
	}
	var remaining int
	if err := target.db.QueryRowContext(ctx, `SELECT count(*) FROM english.lessons WHERE user_id=$1`, runtimeUser).Scan(&remaining); err != nil || remaining != 0 {
		t.Fatalf("账号硬删除后 English 级联剩余 %d: %v", remaining, err)
	}

	source := testStore(t)
	profile, err := source.EnsureProfile(ctx, "home")
	if err != nil {
		t.Fatal(err)
	}
	profile.Difficulty = 2
	if _, err := source.SaveProfile(ctx, profile); err != nil {
		t.Fatal(err)
	}
	sourceLesson, _, err := source.PutLesson(ctx, Lesson{
		UserID: "home", Date: "2026-09-09", Title: "Imported", Passage: "Hello world.", Difficulty: 2,
		Questions: []Question{{ID: "q1", Answer: "A"}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := source.SaveReadingAttempt(ctx, "home", sourceLesson.ID, []Answer{{QuestionID: "q1", Value: "A"}}); err != nil {
		t.Fatal(err)
	}
	if _, err := source.SaveSpeakingAttempt(ctx, SpeakingAttempt{UserID: "home", LessonID: sourceLesson.ID, Score: 80, Accuracy: .8,
		AudioPath: filepath.Join(t.TempDir(), "sample.wav"), Issues: []WordIssue{{Expected: "world", Kind: "misread"}}}); err != nil {
		t.Fatal(err)
	}
	result, err := target.ImportSQLiteUser(ctx, source, "home", importedUser)
	if err != nil {
		t.Fatal(err)
	}
	if result.Profiles != 1 || result.Lessons != 1 || result.ReadingAttempts != 1 || result.SpeakingAttempts != 1 || result.WordResults != 1 {
		t.Fatalf("迁移统计异常: %+v", result)
	}
	importedLesson, err := target.LessonByDate(ctx, importedUser, "2026-09-09")
	if err != nil || importedLesson.UserID != importedUser {
		t.Fatalf("迁移课程 = %+v, %v", importedLesson, err)
	}
	if _, err := target.ImportSQLiteUser(ctx, source, "home", importedUser); !errors.Is(err, ErrEnglishDataExists) {
		t.Fatalf("重复迁移应拒绝覆盖，得到 %v", err)
	}
}
