BEGIN;

CREATE SCHEMA IF NOT EXISTS english;

-- English 在旧 token 迁移期仍需识别 home 等非 UUID 标识，因此 user_id 暂用 TEXT。
-- 规范 UUID 同时生成 account_user_id 外键：平台清除接口是主路径，账号最终硬删除时
-- ON DELETE CASCADE 再兜底一次，防止已通过鉴权的飞行中请求在清除后把数据写回来。
CREATE TABLE english.learning_profiles (
    user_id              TEXT PRIMARY KEY CHECK (btrim(user_id) <> ''),
    account_user_id      UUID GENERATED ALWAYS AS (
        CASE WHEN user_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
             THEN user_id::uuid END
    ) STORED REFERENCES account.users(id) ON DELETE CASCADE,
    cet4_score           INTEGER NOT NULL DEFAULT 430 CHECK (cet4_score > 0),
    level                TEXT NOT NULL DEFAULT 'B1' CHECK (level IN ('A2', 'B1', 'B2', 'C1')),
    daily_minutes        INTEGER NOT NULL DEFAULT 45 CHECK (daily_minutes BETWEEN 10 AND 180),
    goal                 TEXT NOT NULL DEFAULT '',
    difficulty           INTEGER NOT NULL DEFAULT 1 CHECK (difficulty BETWEEN 1 AND 5),
    navigation_position TEXT NOT NULL DEFAULT 'bottom' CHECK (navigation_position IN ('bottom', 'left', 'right')),
    content_mode         TEXT NOT NULL DEFAULT 'balanced' CHECK (content_mode IN ('balanced', 'new-concept', 'ielts', 'china-daily', 'tech')),
    ielts_track          TEXT NOT NULL DEFAULT 'academic' CHECK (ielts_track IN ('academic', 'general')),
    updated_at           TIMESTAMPTZ NOT NULL
);

CREATE TABLE english.lessons (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             TEXT NOT NULL CHECK (btrim(user_id) <> ''),
    account_user_id     UUID GENERATED ALWAYS AS (
        CASE WHEN user_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
             THEN user_id::uuid END
    ) STORED REFERENCES account.users(id) ON DELETE CASCADE,
    lesson_date         DATE NOT NULL,
    title               TEXT NOT NULL,
    passage             TEXT NOT NULL,
    vocabulary_json     JSONB NOT NULL CHECK (jsonb_typeof(vocabulary_json) = 'array'),
    questions_json      JSONB NOT NULL CHECK (jsonb_typeof(questions_json) = 'array'),
    difficulty          INTEGER NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
    generation_reason   TEXT NOT NULL,
    estimated_minutes   INTEGER NOT NULL CHECK (estimated_minutes > 0),
    content_mode        TEXT NOT NULL DEFAULT '',
    exercise_style      TEXT NOT NULL DEFAULT '',
    syllabus_focus      TEXT NOT NULL DEFAULT '',
    source_name         TEXT NOT NULL DEFAULT '',
    source_title        TEXT NOT NULL DEFAULT '',
    source_url          TEXT NOT NULL DEFAULT '',
    source_published_at TEXT NOT NULL DEFAULT '',
    adaptation_note     TEXT NOT NULL DEFAULT '',
    content_hash        TEXT NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL,
    UNIQUE (user_id, lesson_date),
    UNIQUE (id, user_id)
);
CREATE INDEX lessons_user_date_idx ON english.lessons(user_id, lesson_date DESC);

CREATE TABLE english.reading_attempts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        TEXT NOT NULL,
    account_user_id UUID GENERATED ALWAYS AS (
        CASE WHEN user_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
             THEN user_id::uuid END
    ) STORED REFERENCES account.users(id) ON DELETE CASCADE,
    lesson_id      BIGINT NOT NULL,
    answers_json   JSONB NOT NULL CHECK (jsonb_typeof(answers_json) = 'array'),
    correct_count  INTEGER NOT NULL CHECK (correct_count >= 0),
    total_count    INTEGER NOT NULL CHECK (total_count >= 0 AND correct_count <= total_count),
    accuracy       DOUBLE PRECISION NOT NULL CHECK (accuracy BETWEEN 0 AND 1),
    completed_at   TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (lesson_id, user_id) REFERENCES english.lessons(id, user_id) ON DELETE CASCADE
);
CREATE INDEX reading_attempts_user_time_idx ON english.reading_attempts(user_id, completed_at DESC);

CREATE TABLE english.speaking_attempts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          TEXT NOT NULL,
    account_user_id  UUID GENERATED ALWAYS AS (
        CASE WHEN user_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
             THEN user_id::uuid END
    ) STORED REFERENCES account.users(id) ON DELETE CASCADE,
    lesson_id        BIGINT NOT NULL,
    audio_path       TEXT NOT NULL,
    duration_seconds DOUBLE PRECISION NOT NULL CHECK (duration_seconds >= 0),
    transcript       TEXT NOT NULL,
    wpm              DOUBLE PRECISION NOT NULL CHECK (wpm >= 0),
    accuracy         DOUBLE PRECISION NOT NULL CHECK (accuracy BETWEEN 0 AND 1),
    score            DOUBLE PRECISION NOT NULL CHECK (score BETWEEN 0 AND 100),
    feedback         TEXT NOT NULL,
    issues_json      JSONB NOT NULL CHECK (jsonb_typeof(issues_json) = 'array'),
    completed_at     TIMESTAMPTZ NOT NULL,
    UNIQUE (id, user_id),
    FOREIGN KEY (lesson_id, user_id) REFERENCES english.lessons(id, user_id) ON DELETE CASCADE
);
CREATE INDEX speaking_attempts_user_time_idx ON english.speaking_attempts(user_id, completed_at DESC);

CREATE TABLE english.word_results (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             TEXT NOT NULL,
    account_user_id     UUID GENERATED ALWAYS AS (
        CASE WHEN user_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
             THEN user_id::uuid END
    ) STORED REFERENCES account.users(id) ON DELETE CASCADE,
    speaking_attempt_id BIGINT NOT NULL,
    expected_word       TEXT NOT NULL,
    actual_word         TEXT NOT NULL,
    issue_kind          TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL,
    FOREIGN KEY (speaking_attempt_id, user_id)
        REFERENCES english.speaking_attempts(id, user_id) ON DELETE CASCADE
);
CREATE INDEX word_results_user_word_idx ON english.word_results(user_id, expected_word);

CREATE TABLE english.weak_points (
    user_id          TEXT NOT NULL CHECK (btrim(user_id) <> ''),
    account_user_id  UUID GENERATED ALWAYS AS (
        CASE WHEN user_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
             THEN user_id::uuid END
    ) STORED REFERENCES account.users(id) ON DELETE CASCADE,
    point_type       TEXT NOT NULL,
    point_value      TEXT NOT NULL,
    occurrence_count INTEGER NOT NULL DEFAULT 1 CHECK (occurrence_count > 0),
    last_seen_at     TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, point_type, point_value)
);

CREATE TABLE english.weekly_reports (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            TEXT NOT NULL CHECK (btrim(user_id) <> ''),
    account_user_id    UUID GENERATED ALWAYS AS (
        CASE WHEN user_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
             THEN user_id::uuid END
    ) STORED REFERENCES account.users(id) ON DELETE CASCADE,
    week_start         DATE NOT NULL,
    completion_rate    DOUBLE PRECISION NOT NULL CHECK (completion_rate BETWEEN 0 AND 1),
    reading_accuracy   DOUBLE PRECISION NOT NULL CHECK (reading_accuracy BETWEEN 0 AND 1),
    speaking_wpm       DOUBLE PRECISION NOT NULL CHECK (speaking_wpm >= 0),
    problem_words_json JSONB NOT NULL CHECK (jsonb_typeof(problem_words_json) = 'array'),
    summary            TEXT NOT NULL,
    next_focus         TEXT NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL,
    UNIQUE (user_id, week_start)
);

CREATE TABLE english.plan_versions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        TEXT NOT NULL CHECK (btrim(user_id) <> ''),
    account_user_id UUID GENERATED ALWAYS AS (
        CASE WHEN user_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
             THEN user_id::uuid END
    ) STORED REFERENCES account.users(id) ON DELETE CASCADE,
    old_difficulty INTEGER NOT NULL CHECK (old_difficulty BETWEEN 1 AND 5),
    new_difficulty INTEGER NOT NULL CHECK (new_difficulty BETWEEN 1 AND 5),
    reason          TEXT NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX plan_versions_user_time_idx ON english.plan_versions(user_id, created_at DESC);

CREATE TABLE english.job_runs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             TEXT NOT NULL CHECK (btrim(user_id) <> ''),
    account_user_id     UUID GENERATED ALWAYS AS (
        CASE WHEN user_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
             THEN user_id::uuid END
    ) STORED REFERENCES account.users(id) ON DELETE CASCADE,
    job_date            DATE NOT NULL,
    job_type            TEXT NOT NULL,
    status              TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'failed')),
    notification_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (notification_status IN ('pending', 'sending', 'succeeded', 'failed', 'skipped')),
    error_message       TEXT NOT NULL DEFAULT '',
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL,
    UNIQUE (user_id, job_date, job_type)
);

COMMIT;
