"use client";

import { useEffect, useRef, useState } from "react";
import { api, type Lesson, type SpeakingAttempt } from "@/lib/api";
import { Empty, Header, Loading, percent } from "@/components/UI";

export default function RecordPage() {
  const [lesson, setLesson] = useState<Lesson | null>(null); const [loading, setLoading] = useState(true); const [recording, setRecording] = useState(false); const [busy, setBusy] = useState(false); const [seconds, setSeconds] = useState(0); const [error, setError] = useState(""); const [result, setResult] = useState<SpeakingAttempt | null>(null); const [degraded, setDegraded] = useState(false);
  const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]); const timer = useRef<ReturnType<typeof setInterval> | null>(null); const durationRef = useRef(0);
  useEffect(() => { api.today().then(setLesson).catch(e => setError(e.message)).finally(() => setLoading(false)); return () => { if (timer.current) clearInterval(timer.current); recorder.current?.stream.getTracks().forEach(t => t.stop()) } }, []);
  async function start() { setError(""); setResult(null); try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const preferred = ["audio/webm;codecs=opus", "audio/mp4", "audio/ogg;codecs=opus"].find(type => MediaRecorder.isTypeSupported(type)); const r = new MediaRecorder(stream, preferred ? { mimeType: preferred } : undefined); chunks.current = []; durationRef.current = 0; r.ondataavailable = e => { if (e.data.size) chunks.current.push(e.data) }; r.onstop = () => upload(new Blob(chunks.current, { type: r.mimeType || "audio/webm" }), durationRef.current); r.start(1000); recorder.current = r; setSeconds(0); setRecording(true); timer.current = setInterval(() => setSeconds(v => { const next = Math.min(v + 1, 600); durationRef.current = next; if (next >= 600) setTimeout(stop, 0); return next }), 1000) } catch { setError("无法使用麦克风，请在浏览器设置中允许录音权限") } }
  function stop() { if (!recorder.current || recorder.current.state === "inactive") return; recorder.current.stop(); recorder.current.stream.getTracks().forEach(t => t.stop()); if (timer.current) clearInterval(timer.current); setRecording(false); setBusy(true) }
  async function upload(blob: Blob, duration: number) { if (!lesson) return; try { const data = await api.uploadAttempt(lesson.id, blob, Math.max(duration, 1)); setResult(data.attempt); setDegraded(data.degraded) } catch (e) { setError(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  return <div className="min-h-full pb-6"><Header title="朗读训练" subtitle="完整朗读今日短文，系统会对照原文分析" />{loading ? <Loading /> : !lesson ? <Empty>请先生成今日课程</Empty> : <div className="space-y-4 p-4"><section className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="font-bold text-indigo-950">{lesson.title}</h2><p className="mt-3 max-h-56 overflow-y-auto font-serif text-[16px] leading-7 text-slate-700">{lesson.passage}</p></section><section className="flex flex-col items-center rounded-3xl bg-gradient-to-b from-indigo-50 to-white p-8 shadow-sm"><div className={`flex h-28 w-28 items-center justify-center rounded-full ${recording ? "animate-pulse bg-red-500" : "bg-indigo-600"} text-4xl text-white shadow-xl`}>🎙️</div><div className="mt-5 font-mono text-2xl">{Math.floor(seconds / 60).toString().padStart(2, "0")}:{(seconds % 60).toString().padStart(2, "0")}</div><p className="mt-2 text-xs text-slate-400">最长 10 分钟</p><button onClick={recording ? stop : start} disabled={busy} className={`mt-6 w-full rounded-2xl py-3 font-semibold text-white ${recording ? "bg-red-500" : "bg-indigo-600"} disabled:bg-slate-300`}>{busy ? "上传并分析中…" : recording ? "结束朗读" : "开始朗读"}</button></section>{result && <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-bold text-indigo-950">本次反馈</h3><strong className="text-2xl text-indigo-600">{result.score || "—"}</strong></div>{degraded ? <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-700">录音已安全保存。{result.feedback}</p> : <><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Metric label="转写一致度" value={percent(result.accuracy)} /><Metric label="语速" value={`${Math.round(result.wpm)} WPM`} /><Metric label="问题词" value={String(result.issues.length)} /></div><p className="mt-4 rounded-xl bg-indigo-50 p-3 text-sm text-indigo-800">{result.feedback}</p>{result.transcript && <details className="mt-3 text-sm"><summary className="cursor-pointer text-slate-500">查看 ASR 转写</summary><p className="mt-2 rounded-xl bg-slate-50 p-3 text-slate-600">{result.transcript}</p></details>}</>}</section>}{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}</div>}</div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-2"><div className="font-semibold text-indigo-700">{value}</div><div className="mt-1 text-[10px] text-slate-400">{label}</div></div> }
